### ISSUE TITLE
[Main loop] Store message is not getting Favor value from the node

### ISSUE THREAD

**Issue by GportDev** [tntech-ngin/ndn-hydra#22]
```
future: <Task finished name='Task-127' coro=<FileFetcher._fetch_file_helper() done, defined at /home/ubuntu/gabriel/ndn-hydra/ndn_hydra/repo/modules/file_fetcher.py:70> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/ubuntu/gabriel/ndn-hydra/ndn_hydra/repo/modules/file_fetcher.py", line 80, in _fetch_file_helper
    self.store_func(file_name)
  File "/home/ubuntu/gabriel/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 207, in store
    store_message.favor = str(self.global_view.get_node(store_message.node_name)['favor']).encode()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tntech-ngin** [comment]
We think this is due to node_name not being encoded properly. This has since been fixed.
