### ISSUE TITLE
Global view config bug 

### ISSUE THREAD

**Issue by tntech-ngin** [tntech-ngin/ndn-hydra#29]
ndn-hydra-repo -rp /hydra -n /node2
Read handle: listening to /hydra/fetch
Read handle: listening to /hydra/node/node2/fetch
Query handle: listening to /hydra/query
Query handle: listening to /hydra/node/node2/query
Insert handle: subscribing to /hydra/insert
Insert handle: subscribing to /hydra/delete
Subscribing to topic: /hydra/insert
Subscribing to topic: /hydra/delete
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
AttributeError: 'NoneType' object has no attribute 'remaining_storage'
Task exception was never retrieved
future: <Task finished name='Task-32' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
AttributeError: 'NoneType' object has no attribute 'remaining_storage'
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
AttributeError: 'NoneType' object has no attribute 'remaining_storage'
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
AttributeError: 'NoneType' object has no attribute 'remaining_storage'

[Main Loop] [send_heartbeat] Sending heartbeat

[Main Loop] [send_heartbeat] Calculated favor at node /node2: 13

[Main Loop] [send_heartbeat] Global view: 
<module 'ndn_hydra.repo.modules.global_view' from '/home/ubuntu/ndn-hydra/ndn_hydra/repo/modules/global_view.py'>

[Main Loop] [send_heartbeat] Global view at /node2: 
{'node_name': '/node2', 'favor': 1.0, 'state_vector': 176, 'expired': True}
[MSG][CLAIM.R]  nam=/node4;fil=/test_2.txt
Task exception was never retrieved
future: <Task finished name='Task-50' coro=<ClaimMessage.apply() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/claim.py:48> exception=ImportError("cannot import name 'MessageTlv' from 'ndn_hydra.repo.group_messages.message' (/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py)")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/claim.py", line 64, in apply
    from .message import MessageTlv, MessageTypes
**ImportError: cannot import name 'MessageTlv' from 'ndn_hydra.repo.group_messages.message' (/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py)**

[Main Loop] [send_heartbeat] Sending heartbeat

[Main Loop] [send_heartbeat] Calculated favor at node /node2: 13

[Main Loop] [send_heartbeat] Global view: 
<module 'ndn_hydra.repo.modules.global_view' from '/home/ubuntu/ndn-hydra/ndn_hydra/repo/modules/global_view.py'>

[Main Loop] [send_heartbeat] Global view at /node2: 
{'node_name': '/node2', 'favor': 1.0, 'state_vector': 179, 'expired': True}
Task exception was never retrieved
future: <Task finished name='Task-54' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
**AttributeError: 'NoneType' object has no attribute 'remaining_storage'
Task exception was never retrieved**
future: <Task finished name='Task-61' coro=<MainLoop.on_missing_svs_messages() done, defined at /home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py:67> exception=AttributeError("'NoneType' object has no attribute 'remaining_storage'")>
Traceback (most recent call last):
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/main/main_loop.py", line 78, in on_missing_svs_messages
    message = Message.specify(i.nid, i.lowSeqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/message.py", line 54, in specify
    return HeartbeatMessage(nid, seqno, message_bytes)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 37, in __init__
    self.message.favor_weights = self.decode_favor_weights(self.message.favor_weights)
  File "/home/ubuntu/ndn-hydra/ndn_hydra/repo/group_messages/heartbeat.py", line 43, in decode_favor_weights
    'remaining_storage': float(bytes(favor_weights.remaining_storage)),
AttributeError: 'NoneType' object has no attribute 'remaining_storage'

[Main Loop] [send_heartbeat] Sending heartbeat

[Main Loop] [send_heartbeat] Calculated favor at node /node2: 13

**Comment by tntech-ngin** [comment]
We haven't seen this since.
